import {
  Body,
  Container,
  Head,
  Heading,
  Hr,
  Html,
  Preview,
  Section,
  Text,
} from "@react-email/components";
import * as React from "react";

export default function VerificationEmail(props) {
  return (
    <Html>
      <Head />
      <Preview>Algolog 인증메일 입니다</Preview>
      <Body style={main}>
        <Container style={container}>
          <Section style={coverSection}>
            <Section style={imageSection}>
              <div
                style={{
                  textAlign: "center",
                  border: "3px solid white",
                  borderRadius: "25px",
                  backgroundColor: "rgb(135,97,225)",
                  width: "160px",
                  height: "40px",
                  color: "white",
                  fontSize: "24px",
                  fontWeight: "bold",
                  marginLeft: "20px",
                }}
              >
                <span style={{ paddingTop: "10px" }}>ALGOLOG</span>
              </div>
            </Section>
            <Section style={upperSection}>
              <Heading style={h1}>이메일을 인증해 주세요</Heading>
              <Text style={mainText}>
                <div>Algolog에 오신것을 진심으로 환영합니다!</div>
                <div>아래의 인증번호를 입력하여 회원가입을 완료해 주세요!</div>
              </Text>
              <div style={{ textAlign: "center", width: "100%" }}>
                <Text style={verifyText}>Verification code</Text>
                <Text style={codeText}>{props.code}</Text>
                <Text style={validityText}>이 코드는 5분간 유지됩니다</Text>
              </div>
            </Section>
            <Hr />
            <Section style={lowerSection}>
              <Text style={cautionText}>
                <div>만약 본인이 신청한 인증번호가 아니라면 무시해 주세요</div>
                <div>Please Ignore this email if its not generated by you</div>
              </Text>
            </Section>
          </Section>
          <Text style={footerText}>©2024, Park Min Joon</Text>
        </Container>
      </Body>
    </Html>
  );
}

const main = {
  backgroundColor: "#fff",
  color: "#212121",
};

const container = {
  padding: "20px",
  margin: "0 auto",
  backgroundColor: "#eee",
};

const h1 = {
  color: "#333",
  fontFamily:
    "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue', sans-serif",
  fontSize: "20px",
  fontWeight: "bold",
  marginBottom: "15px",
};

const text = {
  color: "#333",
  fontFamily:
    "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue', sans-serif",
  fontSize: "14px",
  margin: "24px 0",
};

const imageSection = {
  backgroundColor: "#8761E1",
  padding: "20px 0",
};

const coverSection = { backgroundColor: "#fff" };

const upperSection = { padding: "25px 35px" };

const lowerSection = { padding: "25px 35px" };

const footerText = {
  ...text,
  fontSize: "12px",
  padding: "0 20px",
};

const verifyText = {
  ...text,
  margin: 0,
  alignText: "center",
  fontWeight: "bold",
  textAlign: "center" as const,
};

const codeText = {
  ...text,
  fontWeight: "bold",
  fontSize: "36px",
  margin: "10px 0",
  textAlign: "center" as const,
};

const validityText = {
  ...text,
  margin: "0px",
  textAlign: "center" as const,
};

const mainText = { ...text, marginBottom: "14px" };

const cautionText = { ...text, margin: "0px" };
